#Load the required packages.
library(tidyverse) #data manipulation
library(ggplot2) #data visualization

#Set working directory where dataset is located.
setwd("C:/Users/Family/Desktop/Term3project_IMS") #change this location to where your files are located.

#Import the dataset.
data <- read.csv("train.csv")

#create a copy of the dataset.
data1 <- data

#remove ID column.
data1$ID <- NULL

#rename variables.
names(data1) <- c("warehouseblock", "modeofshipment", "customercarecalls", "customerrating", "costoftheproduct", "priorpurchase", "productimportance", "gender", "discountoffered", "weightingrams", "reachedontime")

#check for any missing values column-wise.
colSums(is.na(data)) #No missing values in the dataset.

#structure and summary of the dataset
str(data1)
summary(data1)

#check the proportion of target variable - "reachedontime"
table(data1$reachedontime) #4436 orders were delivered on time. 6563 orders were not delivered on time. 


#convert target variable to factor.
data1$reachedontime <- as.factor(data1$reachedontime)

#check for unique levels in the following variables.
unique(data1$priorpurchase) 
unique(data1$customercarecalls)
unique(data1$customerrating)

#convert the above three variables to factor.
data1$priorpurchase <- as.factor(data1$priorpurchase)
data1$customercarecalls <- as.factor(data1$customercarecalls)
data1$customerrating <- as.factor(data1$customerrating)

#structure and summary of the dataset.
str(data1)
summary(data1)

#Delivery rate
prop.table(table(data1$reachedontime))
#On-time delivery rate is 40.33 %
#Delayed delivery rate is 59.66 %

options(scipen = 999) #convert scientific notation to readable numbers

#Average order value = Total Revenue / Total number of orders
sum(data1$costoftheproduct) #2311955 (approx. 2.3 Million US dollars)
averageordervalue <-2311955/10999
averageordervalue #the average amount of money each customer ends up spending per transaction is 210.19 US Dollars
#To improve this value, the e-commerce company should recommend relevant products, set order minimums for discount/free shipping, bundle products.

table(data1$priorpurchase)# Maximum customers in the dataset have made prior purchase of three items
#Minimum number of customers in the dataset have made prior purchases of 8 items

#Revenue generated by customers who have made 3 prior purchases
revenue1 <- data1 %>% filter(priorpurchase == "3") %>% summarise(revenue1 = sum(costoftheproduct))
revenue1 #791585 US Dollars (approx. 791.5 thousand US Dollars)

#Revenue generated by customers who have made less than 6 prior purchases
revenue2 <- data1 %>% filter(priorpurchase == "8") %>% summarise(revenue2 = sum(costoftheproduct))
revenue2 #25590 US Dollars (approx. 25.5 thousand US Dollars)

# CONTINGENCY TABLES
#Warehouse and reached on time.
xtabs(~ warehouseblock + reachedontime, data = data1)
#most activity from the F block of the warehouse

#Mode of Shipment and reached on time.
xtabs(~ modeofshipment + reachedontime, data = data1)
#A large share of deliveries are done with ships

#Customer care calls and reached on time.
xtabs(~ customercarecalls + reachedontime, data = data1)
#maximum customers in the dataset have made 4 calls to customer care.

#Customer rating and reached on time.
xtabs(~ customerrating + reachedontime, data = data1)
#Maximum customers were rated 3, followed by those rated 1.
#882 customers  who have been rated 3, received their orders on time.
#922 custumers who have been rated 1, received their orders on time.
#854 customers who were rated 5, received orders on time, while 1317 customers with the same rating didnt recieve orders on time.

#Prior purchase and reached on time.
xtabs(~ priorpurchase + reachedontime, data = data1)
#majority of the customers have made 3 prior purchases.

#product importance
xtabs(~ productimportance + reachedontime, data = data1)
#most of the customers have purchased products with low importance, It evidently shows the largest delayed time.
#however data also shows that  most customers who bought low priority products had also recieved the products on time.

#discount offered
xtabs( ~ discountoffered + reachedontime, data = data1)
#customers who bought product with less than 11% discount offer/coupons didnt recieve products on time
#while customers who purchased products having more than 11% discount didnt have  delay in recieving the shipment.
max(data1$discountoffered) # 65% discount
min(data1$discountoffered) # 1% discount
#Categorizing the discounts 
describe(data1$discountoffered)#65 unique discount categories
data1$discount_group[data1$discountoffered <=15 & data1$discountoffered>= 1] <- "1" #lowest
data1$discount_group[data1$discountoffered <= 30 & data1$discountoffered >15] <- "2"
data1$discount_group[data1$discountoffered <= 45 & data1$discountoffered >30] <- "3"
data1$discount_group[data1$discountoffered <= 50 & data1$discountoffered >45] <- "4"
data1$discount_group[data1$discountoffered <= 65 & data1$discountoffered >50] <- "5" #highest
data1$discount_group <- as.factor(data1$discount_group)
barchart(data1$discount_group, main = "Discount Categories", sub = "1 indicates Lowest discount category and 5 indicates highest", xlab = "No of customers")

#weight in grams
xtabs(~ weightingrams + reachedontime, data = data1)
#There is no special observation
which.min(data1$weightingrams) #row number 2664 shows product shipped has min weight (1001 grams)
which.max(data1$weightingrams) #row number 200 shows product shipped has max weight (7846 grams)


#data visualization
#Prior Purchase and reached on-time.
ggplot(data1, aes(priorpurchase)) + geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Prior purchase and reached on-time", x = "Number of Prior purchases", caption = "Maximum no. of customers had made prior purchases of three products") 

#Customer rating and reached on-time.
ggplot(data1, aes(customerrating)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Customer rating and reached on-time", x = "Customer rating", caption = "Majority of customers were rated 3, followed by customers who were rated 1 ") 

#Product importance and reached on-time.
ggplot(data1, aes(productimportance)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Product importance and reached on-time", x = "Product importance", caption = "Majority of products were of low importance ") 

#Gender and reached on-time.
ggplot(data1, aes(gender)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Gender and reached on-time", x = "Gender", caption = "Both genders show equal distribution") 

#Warehouse block and reached on-time.
ggplot(data1, aes(warehouseblock)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Warehouse block and reached on-time", x = "Warehouse blocks", caption = "Most activity from the F block of the warehouse") 

#Mode of shipment and reached on-time.
ggplot(data1, aes(modeofshipment)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Mode of shipment and reached on-time", x = "Mode of shipment", caption = "A large share of deliveries were done with ships") 

#Customer care calls and reached on-time.
ggplot(data1, aes(customercarecalls)) + geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Customer care calls and reached on-time", x = "Number of Customer care calls", caption = "Maximum no. of customers in the dataset have made 4 calls to customer care") 

#Histogram for Cost of the product
ggplot(data1, aes(costoftheproduct)) + geom_histogram(breaks=seq(90, 310, by=10), col="red", fill="green", alpha = .2) + 
  labs(title="Histogram for Cost of the product (in US dollars)", x="Cost of the product($)", caption = "The purchase with the highest value is $ 310") 

#Histogram for Weight (in grams)
ggplot(data1, aes(weightingrams)) + geom_histogram(breaks=seq(1000, 8000, by=100), col="red", fill="green", alpha = .2) + 
  labs(title="Histogram for Weight (in grams)", x="Weight(in grams)", caption = "Minimum weight of an order is 1001 grams. Maximum weight of an order is 7846 grams") 

#Histogram for Discount offered
ggplot(data1, aes(discountoffered)) + geom_histogram(breaks=seq(0, 70, by=5), col="red", fill="green", alpha = .2) + 
  labs(title="Histogram for Discount offered", x="Percentage of Discount offered", caption = "Maximum discount offered  by the company is 65 %, and minimum discount offered is 1 %.") 
